# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 13:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogtopic', '0002_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 3, 13, 39, 5, 383176, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
