# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 15:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogtopic', '0004_auto_20160303_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 3, 15, 30, 9, 697785, tzinfo=utc), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='blog_post', verbose_name='Slug for URL'),
        ),
    ]
