# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 20:06
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogtopic', '0010_auto_20160403_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_for_main_page',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Text for the main page:'),
        ),
    ]
